# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      # Do not include build here, Can't run in devcontainer itself
      # - task: build
  build:
    cmds:
      - ./scripts/docker_build.bash
  shell:
    cmds:
      - ./scripts/docker_shell.bash
  fmt:
    cmds:
      - typos . .github .vscode .devcontainer --write-changes
      - dprint fmt
      - git ls-files '*.nix' | xargs nix fmt
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - typos . .github .vscode .devcontainer
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - 'hadolint .devcontainer/Dockerfile'
  deps:
    cmds:
      - nix --version
      - task --version
      - dprint --version
      - typos --version
      - hadolint --version
