name: Lint GitHub Actions workflows
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: get_actionlint
        # Keep same version as used in *.nix
        # https://github.com/rhysd/actionlint/blob/c2c2e495aed3dc2e262680e34eef21d126cfe64f/scripts/download-actionlint.bash#L46C1-L46C8
        # https://stackoverflow.com/a/25563308/1212807
        run: bash -s -- 1.6.25 <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
